apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: threatintelrelay
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: localhost:5000/threatintelrelay-api
      context: src/api
      docker:
        dockerfile: Dockerfile
    - image: localhost:5000/threatintelrelay-airflow
      context: src/pipelines
      docker:
        dockerfile: Dockerfile
  local:
    push: false
deploy:
  helm:
    releases:
      - name: threatintelrelay
        chartPath: deployment/helm/threatintelrelay
        namespace: default
        valuesFiles:
          - deployment/helm/threatintelrelay/charts/api/values.yaml
          - deployment/helm/threatintelrelay/airflow-values.yaml
          - deployment/helm/threatintelrelay/kong-values.yaml
        setValueTemplates:
          api.image.repository: "{{.IMAGE_REPO_localhost_5000_threatintelrelay_api}}"
          api.image.tag: "{{.IMAGE_TAG_localhost_5000_threatintelrelay_api}}"
          airflow.airflow.image.repository: "{{.IMAGE_REPO_localhost_5000_threatintelrelay_airflow}}"
          airflow.airflow.image.tag: "{{.IMAGE_TAG_localhost_5000_threatintelrelay_airflow}}"
        setValues:
          api.image.pullPolicy: "IfNotPresent"