# Kong official chart configuration
kong:
  env:
    database: "postgres"
    pg_host: threatintelrelay-postgresql
    pg_user: kong
    pg_password: kongpassword
    pg_database: kong
  ingressController:
    enabled: true
    installCRDs: false
  proxy:
    enabled: true
    type: ClusterIP
    http:
      enabled: true
      servicePort: 80
    tls:
      enabled: false
  postgresql:
    enabled: true
    auth:
      username: kong
      password: kongpassword
      database: kong