name: CD-docs-website

concurrency:
  group: pages-deploy-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: website
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Cache website deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-website-${{ hashFiles('website/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-website-

      - name: Install dependencies
        run: npm ci
        working-directory: ./website

      - name: Build Astro site
        run: npm run build
        working-directory: ./website

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./website/dist --project-name=${{ secrets.CLOUDFLARE_PAGES_PROJECT_NAME }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}