name: CI-releases

on:
  push:
    branches: [ "release/*", "main" ]
  pull_request:
    branches: [ "release/*", "main" ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    env:
      IMAGE_REGISTRY: localhost:5000
      KIND_VERSION: v0.29.0
      KUBECTL_VERSION: v1.33.2
      HELM_VERSION: 3.18.3
      SKAFFOLD_VERSION: v2.16.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Kind
        run: |
          curl -Lo kind \
            https://kind.sigs.k8s.io/dl/${{ env.KIND_VERSION }}/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/kind

      - name: Install kubectl
        run: |
          curl -Lo kubectl \
            https://dl.k8s.io/release/${{ env.KUBECTL_VERSION }}/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: Install Helm
        run: |
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 \
            | bash -s -- --version v${{ env.HELM_VERSION }}

      - name: Install Skaffold
        run: |
          curl -Lo skaffold \
            https://storage.googleapis.com/skaffold/releases/${{ env.SKAFFOLD_VERSION }}/skaffold-linux-amd64
          chmod +x skaffold
          sudo mv skaffold /usr/local/bin/skaffold

      - name: Create Kind cluster
        run: kind create cluster --name ci-kind

      - name: Initialize Skaffold Helm repositories
        run: |
          skaffold config set --global collect-metrics false
          skaffold diagnose || true

      - name: Build & deploy with Skaffold
        run: |
          skaffold run \
            --default-repo ${{ env.IMAGE_REGISTRY }} \
            --verbosity=debug

      - name: Debug deployment state
        if: failure()
        run: |
          echo "=== Pods ==="
          kubectl get pods -A
          echo "=== Services ==="
          kubectl get svc -A
          echo "=== Events ==="
          kubectl get events --sort-by='.lastTimestamp' -A

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/threatintelrelay-api \
            -n default --timeout=120s

      - name: Smoke test service
        run: |
          kubectl port-forward svc/threatintelrelay-api 8080:80 -n default &
          sleep 10
          curl --fail http://localhost:8080/health

      - name: Delete Kind cluster
        if: always()
        run: kind delete cluster --name ci-kind
