name: CI-releases

on:
  workflow_run:
    workflows: ["CI-all-branches"]
    types:
      - completed
    branches:
      - release/*
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    env:
      # just the registry host—don’t include the image name here
      IMAGE_REGISTRY: localhost:5000
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Kind
        run: |
          curl -Lo kind https://kind.sigs.k8s.io/dl/${{ env.KIND_VERSION }}/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/kind

      - name: Install kubectl
        run: |
          # fetch the latest stable version number
          K8S_VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt)
          curl -Lo kubectl https://dl.k8s.io/release/${K8S_VERSION}/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install Helm
        run: |
          curl -Lo helm.tar.gz https://get.helm.sh/helm-v${{ env.HELM_VERSION }}-linux-amd64.tar.gz
          tar -zxvf helm.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm
          rm -rf linux-amd64 helm.tar.gz

      - name: Install Skaffold
        run: |
          curl -Lo skaffold \
            https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x skaffold
          sudo install skaffold /usr/local/bin/

      - name: Create Kind cluster
        run: kind create cluster --name ci-kind

      - name: Initialize Skaffold Helm repositories
        run: |
          # Let Skaffold initialize its Helm repository configuration
          skaffold config set --global collect-metrics false
          # This will trigger Skaffold to set up any required Helm repos
          skaffold diagnose || true

      - name: Build & deploy with Skaffold
        run: |
          # Add verbose logging to see what's happening
          skaffold run \
            --default-repo ${{ env.IMAGE_REGISTRY }} \
            --verbosity=debug

      - name: Debug deployment state
        if: failure()
        run: |
          echo "=== Pods ==="
          kubectl get pods -A
          echo "=== Services ==="
          kubectl get svc -A
          echo "=== Events ==="
          kubectl get events --sort-by='.lastTimestamp' -A

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/threatintelrelay-api \
            -n default --timeout=120s

      - name: Smoke test service
        run: |
          # forward the HTTP port and check /health
          kubectl port-forward svc/threatintelrelay-api 8080:80 -n default &
          sleep 10
          curl --fail http://localhost:8080/health

      - name: Delete Kind cluster
        if: always()
        run: kind delete cluster --name ci-kind
