name: CI-releases

on:
  workflow_run:
    workflows: ["CI-unit-tests"]
    types:
      - completed
    branches:
      - release/*
      - main

jobs:
  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    env:
      # just the registry host—don’t include the image name here
      IMAGE_REGISTRY: localhost:5000
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.17.0
          registry: false

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.11.1'

      - name: Set up Skaffold
        uses: heypigeonhq/setup-skaffold@v1.1.0
        with:
          version: 'latest'

      # --- make Skaffold load images directly into Kind rather than push/pull ---
      - name: Enable Skaffold “local-cluster” mode
        run: skaffold config set --global local-cluster true

      - name: Create Kind cluster
        run: kind create cluster --name ci-kind

      - name: Build & deploy with Skaffold
        run: |
          # this will:
          #   1) docker-build your images
          #   2) load them straight into the Kind cluster
          #   3) helm-deploy via your skaffold.yaml
          skaffold run \
            --default-repo ${{ env.IMAGE_REGISTRY }}

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/threatintelrelay-api \
            -n default --timeout=120s

      - name: Smoke test service
        run: |
          # forward the HTTP port and check /health
          kubectl port-forward svc/threatintelrelay-api 8080:80 -n default &
          sleep 10
          curl --fail http://localhost:8080/health

      - name: Delete Kind cluster
        if: always()
        run: kind delete cluster --name ci-kind
